include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false

linter:
  rules:
    always_use_package_imports: true
    avoid_returning_null_for_future: true
    cancel_subscriptions: true
    close_sinks: true
    only_throw_errors: true
    prefer_single_quotes: true
    sort_child_properties_last: true